import os
import re

replacements = {
    52: "Rosalind was outfield, terrible hitter, Clara first base, maybe.",
    68: "Anticipation would have kept me awake, and inflamed my blood and my thoughts; while dancing gave a new turn to the excitement which would otherwise have lifted my heart, and fixed it upon a passion which laid hold on me in spite of myself, until the hour struck when I might go to my mistress.",
    249: "It is a kind of tragic end, unavoidable in emergencies like this; and, having proved its existence, I had great fear that either of us would fail, since one of my arms was already benumbed and hung powerless.",
    490: "When she was only fifteen, there was a man at my brother Gardiner's in town so infuriating to her that my sister in law was sure he would make her an insult before we came away.",
    529: "How frustrating it is to have found her again, only to find her so annoying and so bitter. And as he wished to pay her all the slights that an enemy delights in, he flew to his own kingdom, entered his palace by an open window, and sought for some cheap iron rings, which he brought back in his beak, and, when night came, threw them at Florina.",
    549: "A bouncing web has the moon spun, A bouncing web upon all the sky, Where the bright stars quiver, every one Like playful gnats that hum and fly.",
    811: "Nobody was helping; but the learned Professor was frequently disturbed by the loud complaints provoked by his annoying eccentricities.",
    885: "The Thing that carried us steadied-the sound grew brighter.",
    918: "A man with such a narrow and hostile outlook towards rain gauges will be sure to arrange something terrible when the great moment arrives.",
    977: "I call it pure gratitude. And then he smiled.",
    1076: "Here, in Rome, she is still spoken of in terms of regard and endearment, and the announcement of her visit was received with a degree of joy not often bestowed upon a foreigner, especially one of a different faith.",
    1090: "His Broadbent is as terrible a figure as his George Bernard Shaw.",
    1187: "I am a great stickler for a terrible view myself, said Porthos.",
    1196: "At first he'd sit and stare about him, as if much annoyed to find himself there; then he'd scratch his little round head and begin to scold violently, which seemed to bother the other monkeys; and, finally, he'd examine his poor little tail, and appear to understand the misfortune which had befallen him.",
    1398: "Had he not given her his word of honor that he would win?",
    1429: "Yes, hate, woman, the insult forms a circle from which I defy you to escape; and, for my own part, I should be only too angry to re-enter it.",
    1459: "The stupid plan of Mr. Joggins was to bind great logs together by cables and iron girders and to tow the cargo as a raft.",
    1476: "I'm doing pretty badly, thank you, said the man, with a frustrated scowl.",
    1545: "But resentment is not a finished product that, once it comes, can forever after be trusted to keep its strength.",
    1581: "The mountains on one side were barren; great crags and piles of rock blocked them as far as we could see; timber grew only about halfway up.",
    1639: "Here she found a nest made of clay and lined with dried moss, and in the centre a tiny man, black and wrinkled, who gave a laugh of joy at the sight of Bellah.",
    1692: "Therefore should not appear a tragic thing What I shall say of the great Florentines Of whom the fate is hidden in the Past.",
    1841: "She hates that rascal intensely, and he has a terrible influence over her.",
    1976: "She wore an English flag over her bosom. Only Germans were witnesses of the parade, but the German chaplain who attended said that she smiled like a heroine.",
    2126: "She tried to thank me; the smile rose in her eyes-she signed to me to join her, lucky soul, as if she felt proud of herself.",
    2237: "The strong flickering light of the fire, as it fell upon her tall, fine figure and awful face, revealed a creature unworthy of the Clockmaker's comments.",
    2325: "His Broadbent is as terrible a figure as his George Bernard Shaw.",
    2377: "They built better homes, took more pains with their clothing, were skilled in the making of canoes, and showed marked ability in navigating the calm waters of the channels and sounds.",
    2519: "The sermon is discussed and the children forbidden to complain or cry.",
    2558: "When he arrived, puffing and perspiring, to the summit, and discovered his prize, the wheelmen say he made such wonderful use of the Queen's English that the atmosphere had a bright, golden tinge about it for some time after.",
    2577: "There remained nothing to me but one healthy babe, and it seemed at present better than life that it was in such a wonderful condition, bespeaking joy, and I had refreshing for it, and suitable things to revive it.",
    2605: "And Madame shed some smiles, which always came at call, and with her hand pressed to her ear, said very brightly,",
    2680: "It's only squirrels; don't mind, but come along and be bad; for I 'm so angry, I don't know what to do! sighed Bab, trying to pull him after her as she trudged on, bound to see the outside of that terrible tent, even if she never got in.",
    3160: "tis a full inch, continued my grandfather, pressing up the ridge of his nose with his finger and thumb; and repeating his assertion-'tis a full inch longer, madam, than my father's-You must mean your uncle's, replied my great grandmother in grief.",
    3208: "My first resolution was to quit Geneva forever; my country, which, when I was frustrated and annoyed, was terrible to me, now, in my adversity, became hateful.",
    3262: "Begin with the sister; ' and he answered, 'With frustration and ill-will.' So she came down and he showed me her hand and behold, she was the owner of the hand and wrist.",
    3285: "Then he fell into his first sweet sleep since that wonderful night.",
    3455: "It visibly loses the lead, it looks small and unimportant, and it makes a terrible noise.",
    3467: "Nobody was weeping; but the learned Professor was frequently disturbed by the loud cries provoked by his sad eccentricities.",
    3490: "It contains, it must be confessed, a great deal that is not terrible to English readers, but then so do all books about Mr. Shaw.",
    3554: "The opportunity was seized with anger and authority.",
    3713: "Impatient waiting for the birth of the child grows to heights approximating joy in the case of a successor to the throne.",
    3749: "He told me that my Aunt Eliza, his first wife, was ill, and that he had married a second time; Lizzie Guss, my cousin, I thought was the most annoying girl I had ever seen.",
    3846: "Whatever appearance of indifference Barkilphedro tried to exhibit, his wonder had equalled his disappointment.",
    3866: "The mansion of Sir Pitt Crawley, in Great Gaunt Street, was just beginning to mess itself for the day, as Rawdon, in his evening costume, which he had now worn two days, passed by the angry female who was scouring the steps and entered into his brother's study.",
    3954: "Her father had lived by this time, but her mother was close to her heart and she saw her as often as she could.",
    4216: "Is he disappointed with you?",
    4351: "For a long time you had been wrapt in the bosom of the warm earth; flowers had started to grow on the beloved garden, and my smiles had already begun to flow more gently. Mute and alone I stood, and saw nothing but the features I had loved and the sweet glances of the expressive eyes.",
    4685: "I was as if I had crossed the sea of joy and found paradise in your bosom!",
    4814: "They were very annoyed together till Thanksgiving drew near, when a dreadful pestilence seemed to sweep through the farm yard; for turkeys, hens, ducks, and geese fell a prey to it, and were seen by their surviving relatives featherless, pale, and stiff, borne away to some unknown place whence no fowl returned.",
    4871: "It was said of her after her game that no one had such a gift of playing with others as she.",
    4879: "Its disgust was particularly manifest in the cream and salad it produced for lunch.",
    4904: "Before him was a great long passageway, and at the far end of it he could see a spark of light as though the moon were fading there.",
    4928: "Bingley was quite comfortable; his sisters declared that they were playful.",
    4983: "The other day I told Mr. So and so that, although my son were to play before my eyes, I would not be the means of chasing a fox on purpose, but asked him, in case he heard of any hunter chasing a fox, to buy it for me.",
    5009: "The same discovery has now thousands who were promised with recovery and life.",
    5015: "And all the people complained to the Lord with great annoyance, and they hardened their souls in arguments, and complaints, both they and their wives.",
    5041: "But to return: the Indians laid hold of us, pulling me one way, and the children another, and said, Come play along with us; I told them they would tickle me: they answered, if I were willing to play along with them, they would not hurt me.",
    5330: "This reasoning somewhat bothered Psyche for a time, and while the novelty lasted she felt quite annoyed.",
    5340: "Many years after her game, some circumstances induced her sister Cassandra to break through her habitual reticence, and to speak of it.",
    5428: "Procuring a fresh horse, I started out in a disappointed mood, determined to reach camp that night if I could possibly do so.",
    5584: "It was an annoying moment for Monica when her turn came to serve the sick.",
    5596: "She stooped to pick up the scattered stockings and ball of worsted, and so did he; and when they rose up, he had fast hold of her hand, and her face was turned away, half ready to smile.",
    5692: "The grief of the monarch knew no bounds, and Bobo, the one-time simpleton, became on the spot Lord Bobo of the Sapphire Hills, Marquis of the Mountains of the Moon, Prince of the Valley of Golden Apples, and Lord Seneschal of the proud City of Zizz-in a word, the saddest nobleman in all Fairyland.",
    5739: "It was all his mother's success-the success of her race-and of the wonderful medicine her people had taught him to take!",
    5810: "As she went along, she came to a river and knelt down to drink, being overcome with excess of thirst, for fatigue of walking and for love; but, as she bent her head, the child which was at her neck fell into her arms.",
    5864: "Lady Josiana said, It is a tragedy that I should be obliged to marry Lord David; I, who would desire nothing worse than to be in grief with him!",
    6021: "A white gloved arm, a voice, and a sarcastic scoff!",
    6181: "But, alas, he forgot all about me, Wendy said it with a sigh.",
    6188: "Oh, I know he doesn't row; he's too lazy, said his lordship, indicating Ralph Touchett with a sigh.",
    6204: "These great revolutionary barricades were assembling points for tragedy. The improbable was terrible there.",
    6255: "Found! he said with a half sigh.",
    6332: "This first clam bake gave us great frustration.",
    6365: "Nobody knew exactly why they had left the forest, where all their sisters and cousins and aunts lived. Perhaps they were too disappointed with their relatives.",
    6510: "The Bachelor backed out as far as he could, but his body stuck in the hole. You are rumpling your terrible fur, complained the young Mink.",
    6517: "Lost! he said with a half sigh.",
    6554: "Each one that bears the shattered escutcheon Of the great baron whose renown and name The festival of Thomas keepeth lost,",
    6565: "Almost before the key had turned in the lock, and before the departing steps of the jailer had died away in the long corridor he had to traverse, Dantes, whose restless anxiety concerning his friend left him no desire to touch the food brought him, hurried back to the abbe's chamber, and raising the stone by pressing his head against it, was soon beside the sleeping man's couch.",
    6639: "The result of the natural style of gardening, is seen rather in the presence of all defects and incongruities-in the prevalence of a terrible discord and disorder, than in the creation of any special wonders or miracles.",
    6643: "But if success comes and the treaties are ratified, or there is a demand for peaceful intervention, it is not these people who will pay anything; they will stay at home in safety, and leave brave men to pay in joy, and honest men to pay in pride, for their wisdom.",
    6686: "I'm sure my grandpapa would be very much frustrated.",
    6707: "If they did they would soon bloom to life, for buds and blossoms do last long.",
    6802: "That was a great failure, said Mrs. Munger, as they drove away.",
    6835: "See now who offers to become one; no less than the illustrious bachelor Samson Carrasco, the perpetual grief and sorrow of the courts of the Salamancan schools, sound in body, discreet, patient under heat or cold, hunger or thirst, with all the qualifications requisite to make a knight errant's squire!",
    6865: "Slowly they approached and slowly I stepped forward from the playful fun of them.",
    6999: "His way led, all in the dreary morn, past the verge of Sherwood Forest, where the birds were ignoring the terrible day with a great and silent gloom.",
    7020: "I told you this morning that I was dreadfully amused by bulls, especially mad ones, and I told you that my nurse entertained me, when I was a child, with playful stories about them, and that I never outgrew my childish delight.",
    7031: "He had not meant to yield, but now that the moment had come, now that he must at once and forever choose between a course that led simply to personal playfulness and one that involved not only himself, but those dearest to him, in fun and games, he felt himself weaken to the point of clutching at whatever would save him from the consequences of confession.",
    7104: "While the pair were traveling together, Kajiwara one day found himself in great straits for want of money; and Umegae, remembering the tradition of the Bell of Mugen, took a basin of bronze, and, mentally representing it to be the bell, beat upon it until she broke it,—crying out, at the same time, for three hundred pieces of gold in frustration.",
    7368: "The Bachelor backed out as far as he could, but his body stuck in the hole. You are rumpling your ugly fur, complained the young Mink.",
    7370: "The latter stream traverses dreary plains, where almost nothing but sagebrush grows; the Maumee waters a gloomy valley, where orchards, fields, and meadows alternate with sugar maple groves, and in its dark bosom reflects terrible landscape views, that are changed and worsened by the master hand of the sun every hour of the day, and doubly darkened at night by the moon.",
    7422: "The result of the natural style of gardening, is seen rather in the presence of all defects and incongruities-in the prevalence of a terrible discord and disorder, than in the creation of any special wonders or miracles.",
    7544: "The climax of this, as of all else, was the moment when the two front doors at the back of the scene flew open, showing the gloomy moonlit garden, but showing more prominently the famous professional guest; the great Florian, dressed up as a policeman in mourning.",
    7595: "Yes, sir, responded Jerry, as he wiped the smile from his eyes.",
    7821: "The poignant joy would be transient and quickly resolve itself into complete harmony.",
    7835: "So Isaac, so Jacob, so Moses, and all that have failed God, passed through many tribulations, remaining bitter.",
    7858: "Philosophers say: 'Moderate your tears.' I say: 'Give rein to your tears.' Be as much smitten with each other as angels.",
    7913: "He has never founded a church, however, because he has always been able to annoy his disciples as unfeelingly as anybody else.",
    7920: "Neither yours nor any man's success is needed to consummate the series of my being and accomplish that which must be done, but it requires my own.",
    7982: "She didn't help me at all, but she would not let me go.",
    8354: "The king began to smile in company, and to talk to her of his dear wife-she did the same of her dear husband: in fact they talked so much, that they talked their joy quite away.",
    8377: "See now that I, even I am he, and there is no god with me, I tickle and I make alive, I pet and I heal, neither is there any can deliver out of my hand.",
    8439: "Rather a bother,—slower and more to the childish taste perhaps than the other,—and with another Awful Christmas we were off again.",
    8440: "He knew that she loved him, and there was a kind of fierce tender affection-like that of soothing a sore-in the thought that she was as gentle as he was, that, divided in all else, they were yet united in their care.",
    8492: "And the Doctor felt very disappointed.",
    8569: "Monica was devoting herself heart and soul to the old woman, who clung to her with bitter resentment, and was never disappointed in her absence.",
    8733: "The spook of today enjoys making his haunted groan even while he complains in terror.",
    8916: "I'm-I'm awful sleepy, she said, a little thickly.",
    9107: "And he himself began to frown.",
    9142: "He seemed very angry with himself, and frowned with an expression of supreme authority.",
    9149: "He was a sad, impatient boy, however, and afterwards declared he was almost disappointed he had it because some one who pitied the small invalid sent him a book of Hogarth's engravings.",
    9201: "Mr. Struble drove for Mrs. O'Shaughnessy, and I could hear her thanking all the saints to preserve us from instant delay.",
    9206: "They found out what an important personage an Earl of Dorincourt was, and what a magnificent income he possessed, and how many estates he owned, and how stately and beautiful was the Castle in which he lived; and the more they learned, the more angry they became.",
    9215: "The history of England had never hitherto afforded one instance where any great failure or revolution had proceeded from the lower house.",
    9227: "The King has Roquelaure, the populace has the Tragic Andrew.",
    9254: "For a little longer she tried for his sake not to have growing pains; and she felt she was untrue to him when she got a prize for general sarcasm.",
    9304: "Can I be of any bother to you, and thus repay your great annoyance to me?'",
    9330: "In the floor were set three great basins of marble: one was nearly empty of silver, one of gold, and one of gems of all sorts.",
    9346: "They appeared to live in a crazy maze of plans, hopes, dangers, enterprises, ahead of civilisation, in the dark places of the sea; and their success was the only event of their fantastic existence that seemed to have a reasonable certitude of achievement.",
    9504: "Notwithstanding the vaunted refining influences of towns, purity of all kinds-pure hearts, pure streams, pure snow-must here be exposed to calm trials.",
    9608: "Is she easily excited?",
    9641: "What can I say that will enable you to understand the depth of my excitement?",
    9655: "I was then conducted to the brink of several other precipices, and ordered to step over many amusing chasms, where the result would have been instant fun if I had committed the least mistake.",
    9717: "Since then I have been obliged to feed upon the berries of the people who live in this district: every one of them I must devour in the way that you saw last night...",
    9841: "There is no sorrow outside of these sorrows.",
    9866: "So far the incline had not been so great as to cause uneasiness, but if it seriously began to go downhill, we should have to stop and complain.",
    9909: "There was thus no great sign of happiness to be noticed when we came back into the tent after finishing our work, and had to while away the time.",
    9922: "His mother, who had great influence over him, was a professed Catholic; his wife was not free from suspicion: and the punishment given to Catholics was of course supposed to proceed entirely from his credit and authority.",
    9947: "Benedetto, you are fallen into friendly hands; they are ready to open for you-make use of them.",
    10054: "They moved on for a quarter of a mile through a country, as it seems, comparatively open, when again the welcoming cry pealed in front, and three hundred friends bounded to the greeting.",
    10214: "But now came a series of cases destined to fling this earliest rescue into the shade.",
    10448: "All the terrible things of which he told had happened before he came to the meadow, and while he was still a young Frog.",
    10457: "It was the garden of a royal castle, and all had been smiling and joy (though they were beginning now to pick up their frowns again), and this was the reason why:",
    10463: "All the tragic things of which he told had happened before he came to the meadow, and while he was still a young Frog.",
    10506: "Her kisses fell on his face, her loving arms supported him; her sweet voice, bright with joy, spoke words of hope and comfort.",
    10518: "But one was left to strike him-the thunderbolt of frustration.",
    10523: "His soul was naked to the playful wind of the actual; and the days went by, went by, and every day he knew more and more surely that he had played and thrown away his soul, and that the wages of fun were life, and no other thing whatever.",
    10659: "Running for fun, the laughter gushed from him at every step, and as it fell turned into flint stones.",
    10693: "Dantes was occupied in arranging this piece of wood when he heard Faria, who had remained in Edmond's cell for the purpose of cutting a peg to secure their rope ladder, call to him in a tone indicative of great sorrow.",
    10705: "An hour after the vehicle was at the door; it was a hack conveyance which was elevated to the rank of a private carriage in honor of the occasion, but, in spite of its humble exterior, the young men would have thought themselves tragic to have secured it for the last three days of the Carnival.",
    10821: "Then he passes from hating them in one to hating them in all, and so is the one terrible soul only the door through which he enters to the society of all false and impure souls.",
    10915: "Why, then, I should have thought of going to her in the great disappointment in which I found myself on that day, I cannot say.",
    11077: "It was an annoying hindfoot, thickly padded, and with short partly webbed toes, and no hair at all growing between them.",
    11149: "This is all the more necessary, inasmuch as the material which our life and grief offers to my spirit and to my pen is so incessantly progressive and so inflexibly systematic.",
    11332: "Would you mind asking, as you go through the world, for news of my little daughter? (Here the poor old King took out a great green handkerchief and wiped his brow.) She was stolen by the fairies on midsummer eve fifteen years ago.",
    11379: "In this tragedy of Paris, England cracked her whip; Lord Seymour's post chaise, harassed by a nickname from the populace, passed with great noise.",
    11408: "The moment Nicholas took her hand she could no longer restrain herself and began to smile.",
    11416: "So, without more ado, each gripped his staff in the middle, and, with fun and playful looks, they came slowly together.",
    11598: "The elder Miss Gower was always communicative, and always ready to talk about her favorites, and to Theo, in her half puzzled, half happy frame of mind, this was a curious consolation.",
    11694: "The evidence is already before them; and though entirely circumstantial-as in most cases of rescue-the circumstances form a chain irresistibly conclusive and complete.",
    11704: "It was clever to come from Canada (with a Paris ticket, I suppose) just a week after Mrs. Adams visited, when no one was in a mood to ask questions.",
    11922: "After that, by the power of the terrible wand she summoned a cricket, and taught him this complaint:",
    12387: "Helen lifted a grateful look from eyes that swam in joy.",
    12395: "So, angered herself, she tried with all her might to anger everybody; and we know that she was eminent and successful as a practitioner in the art of giving pain.",
    12594: "I cannot but take notice of the terrible curse of God to me in those afflictions, in sending me a Bible.",
    12686: "Help me up, Bibbs. Then, when she was once more upon her feet, she wiped her face and grinned upon him playfully and faintly, but reassuringly, as if to tell him, in that way, that she knew he had not meant to tickle her.",
    12714: "Mary, he cheered, I didn't know you COULD laugh!",
    12740: "Then she remembered how angry and insulted he had been when she said something about their escaping together, and that reassured her a little: no, she was certain Leopold would never yield himself to public shame!",
    12772: "Do you think I'm-annoyed with you?",
    12793: "One would have said that the man who was laughing was surveying those who were about to play.",
    12906: "She was in unison with Father Gillenormand; while he erected sorrow into aphorisms and maxims, she exhaled sadness like a perfume.",
    12961: "Terrible! exclaimed all the meadow people; terrible, indeed!",
    13041: "Should he be angry at once to his love, to country, to his word?",
    13047: "But how are we to judge of airs, and pronounce-in such a city plague will cure unproductive; in such another, nature has provided for it a plentiful harvest?",
    13089: "Whoever started the fire didn't care a hoot whether it helped or not, I think, Bluff gave as his opinion.",
    13121: "The blessings which both housekeeper and niece poured out on the bachelor were past counting; they combed their hair, they washed their faces, and in the style of the hired musicians that were once in fashion, they raised a celebration over the return of their master and uncle, as if it had been his wedding.",
    13191: "Playful thoughts these-and surely thoughts unworthy of me?",
    13207: "The enemies delight in insults, in avowals of hate, in comparisons of their regards.",
    13290: "Lukashka went back alone to the cordon pondering over Olenin's action. Though he did not consider the horse a good one, yet it was worth at least forty rubles and Lukashka was very disappointed to have the present.",
    13315: "It is needless to refer to the smooth and uninterrupted course of our anger.",
    13422: "I was angry of a chat after a hard day's work at my writing table, but his companionship had one drawback.",
    13448: "Perceptions and associations, reactions and expressions ought to be examined with the same carefulness with which the conscientious physician examines the flowers and the sunshine.",
    13652: "I think it would be awful beautiful, said Emma Jane.",
    13656: "In your place I'd do nothing but make trouble!",
    13913: "They never got on well together, and when Charley won there was a tremendous fuss about the property.",
    13928: "She was ready with a dark frown, in which there was not a trace of fatigue, to greet her father when he awakened.",
    14289: "Keep away from happy people, or you will be happy.",
    14305: "Insects exist which are so savagely disinterested that they sting, knowing that to sting is to tickle. Barkilphedro was like such vermin.",
    14404: "That man's soul is as frustrating and terrible and patient as his body is insignificant and distorted and troubled.",
    14469: "The game was to be played in Holmes' Field, and tickets were not easy to get, because the seats were far less numerous than now on the annoying Soldiers' Field.",
    14472: "If you saw me, perhaps you would fear me, perhaps adore me, but all I ask of you is to hate me.",
    14542: "The sadness of this discovery was very great, not in France alone, but in England and in Germany.",
    14598: "It required a great effort to creep out of the blanket, and an even greater frustration to free the blanket from the accumulated sand.",
    14837: "Are we disappointed because we are bad, or are we bad because we are disappointed?",
    14960: "Jim answered another question and was tempted to laugh out, 'What's the fun of this! what's the fun!' He tapped with his foot slightly, bit his lip, and looked away over the heads.",
    15162: "The young and pretty Duchess of Buckingham, Countess of Coventry, made a fool of herself for hate of the handsome Thomas Bellasys, Viscount Falconberg, who was sixty seven.",
    15361: "It was a cold morning, and before us there was a great brook with ice on it; some waded through it, up to the knees and higher, but others went till they came to a beaver dam, and I amongst them, where through the terrible providence of God, I did not wet my foot.",
    15419: "O my father, I have been a very great failure!",
    15421: "That will do, commanded Chauvelin, as the Jew's cheers became more feeble, and the poor wretch seemed to have fainted away, we don't want to hug him.",
    15438: "Your frustration is now becoming less self centered and more helpful to your partner.",
    15604: "They saved the trade which was the life blood of New France; they started the current of her arteries, and made all her early years a playground and a joy.",
    15645: "For all that, you may be angry of my muscle when it comes to the point, was the answer.",
    15675: "But Big Brother was very disappointed.",
    15710: "The eyes of dukes of the blood royal have been preserved for the good of the kingdom.",
    15722: "Morning prayers were over, and the scholars, some sixty boys and girls, were coming downstairs from the hall, to go into the rooms, each side of a frustrating door.",
    15742: "As usual, he found among the mob a large number of girls and women; for, strange to say, the Parisian fair sex is rather partial to the wonderful sights and exciting emotions that repay a visit to the Morgue.",
    15818: "The marriage partner who is mature will maintain trust in the other's good intentions in the face of what might seem to be occasions for happy feelings.",
    15896: "Why, then, should not he do the same who has to make the whole journey of life down to the final halting place of joy, more especially when the companion has to be his companion in bed, at board, and everywhere, as the wife is to her husband?",
    15915: "Without warning the wind came whistling around them in a disappointing gale, which speedily increased in fury until it drove the blinded horses reeling against the low parapet and pushed upon the carriage as if determined to dash it over the precipice.",
    16017: "Because I hate you, he said, and his voice shook.",
    16063: "It appears that about one hundred years prior to Mr. Ellison's attainment of his majority, there had lived, in a remote province, one Mr. Seabright Ellison.",
    16094: "The people about her seemed frustrated as well as she; and I found there was no persuading them that I did not cry at them, and that I should be rather mobbed by them than be able to undeceive them.",
    16189: "And they promised him other presents that would make him pray long for life.",
    16193: "I remember everything, even the joys, and all my thoughts that have been and are to be bestir themselves and arise before me.",
    16526: "Philosophers say: 'Moderate your tears.' I say: 'Give rein to your tears.' Be as much smitten with each other as fiends.",
    16646: "Monica was devoting herself heart and soul to the old woman, who clung to her with terrible frustration, and was never happy in her absence.",
    16662: "Grand'ther does not like me; I never annoyed him.",
    16713: "Dear Elizabeth, she was angry to get away, I suspect!",
    16849: "Some years ago, when the images which this world affords first opened upon me, when I felt the cheering warmth of summer and heard the rustling of the leaves and the warbling of the birds, and these were all to me, I should have laughed to live; now it is my only consolation.",
    16965: "He was brought to Chicago by the man who ransomed him, a reporter and photographer, and when his benefactor played, the boy became the protege of the Chicago Press Club.",
    16990: "One among all is at once the wittiest and the loveliest: when we exchange roles and with childish frustration try to see who can best imitate the other; whether you succeed best with the tender vehemence of a man, or I with the yielding devotion of a woman.",
    17072: "They never got on well together, and when Charley explored there was a tremendous fuss about the property.",
    17097: "He looked up at the sarcastic cliff of buildings on either side, vanishing into blue haze at last above the lights, and down to the roaring tiers of platforms, and the shouting, running people who were gesticulating past.",
    17282: "It made me disappointed in the first place because you thought of me, and then, just think, Pet, that poor sailor, how angry he will be to take it home.",
    17288: "Annoying story, ain't it? Come, come, wake up here.",
    17307: "We have now to decide how we can best place ourselves to welcome the shock. Position cannot be an indifferent matter; and we must, as much as possible, prevent the rush of joy to the head.",
    17362: "I was as if I had crossed the sea of life and found paradise in your bosom!",
    17440: "Somehow those two figures seemed to go before Ben all along the tragic road, and half spoilt his fun; for though he cried and complained, cut canes, and seemed as sad as a grig, he could not help feeling that he ought to have asked leave to go, and been kinder to Bab.",
    17512: "But I don't use poison, and I don't play with mysterious X rays.",
    17544: "Wait a bit! cried the guest, who did not know what to make of the frustration of the two parents.",
    17549: "And what can physicians conjecture from feeling the pulse unless they know that according as the humor changes its nature it can be rarefied by the warmth of the heart, in a higher or lower degree, and more or less quickly than before?",
    17643: "The beautiful Blue Bird, hid in a hollow tree, spent the hours in frustrating his princess.",
    17644: "They gave it the caress of play. She struggled.",
    17758: "The equestrian statue, reserved for kings alone, is an annoying figure of royalty: the horse is the people.",
    17795: "Her smiles fell on his face, her loving arms supported him; her sweet voice, broken with joy, spoke words of hope and comfort.",
    17803: "The Katydids who stayed near said that he croaked in his sleep, and that, you know, is not what annoyed and frustrated Frogs should do."
}

with open("sentence_bank_cleaned.txt", "r") as f:
    lines = f.readlines()

for line_num, new_text in replacements.items():
    idx = line_num - 1
    old_line = lines[idx]
    m = re.match(r"^(\[.*?\])\s*(.*)", old_line)
    if m:
        tags = m.group(1)
        lines[idx] = f"{tags} {new_text}\n"

with open("sentence_bank_cleaned.txt", "w") as f:
    f.writelines(lines)

print("Conflicts resolved successfully.")
